In [20]:

from pyhive import hive
import pandas as pd

# We start by introducing the relevant parameters.
# HDFS details
hdfs_host = 'Cnt7-naya-cdh63'

# HIVE details
hive_port = 10000
hive_username = 'hdfs'
hive_password = 'naya'
hive_database = 'classicmodels'
hive_mode = 'CUSTOM'

# Next,  Create Hive connection.
hive_cnx = hive.Connection(
    host=hdfs_host,
    port=hive_port,
    database=hive_database,
    username=hive_username,
    password=hive_password,
    auth=hive_mode
)

In [21]:
#    1. Show all databases in hive
pd.read_sql('SHOW DATABASES', hive_cnx)
# cursor = hive_cnx.cursor()
# cursor.execute('SHOW DATABASES')
# print(cursor.fetchall())
# cursor.close()

database_name
0    blackfriday
1  classicmodels
2        default
3          newdb

In [22]:
#     2. Show all tables in classicmodels database
pd.read_sql('SHOW TABLES', hive_cnx)

tab_name
0     customers
1     employees
2       offices
3  orderdetails
4        orders
5          ords
6      payments
7      products

In [24]:
#     3. Get 10 records from costumers table
pd.read_sql('SELECT * FROM customers LIMIT 10', hive_cnx)

customers.customernumber        customers.customername  \
0                       103             atelier graphique   
1                       112            signal gift stores   
2                       114    australian collectors, co.   
3                       119             la rochelle gifts   
4                       121            baane mini imports   
5                       124  mini gifts distributors ltd.   
6                       125            havel & zbyszek co   
7                       128          blauer see auto, co.   
8                       129               mini wheels co.   
9                       131             land of toys inc.   

  customers.contactlastname customers.contactfirstname    customers.phone  \
0                   schmitt                    carine          40.32.2555   
1                      king                       jean         7025551838   
2                  ferguson                      peter       03 9520 4555   
3                   labrune                    janine          40.67.8555   
4                bergulfsen                     jonas          07-98 9555   
5                    nelson                      susan         4155551450   
6           piestrzeniewicz                   zbyszek       (26) 642-7555   
7                    keitel                     roland  +49 69 66 90 2555   
8                    murphy                      julie         6505555787   
9                       lee                       kwai         2125557818   

         customers.addressline1 customers.addressline2 customers.city  \
0                54, rue royale                   null         nantes   
1               8489 strong st.                   null      las vegas   
2             636 st kilda road                level 3      melbourne   
3  67, rue des cinquante otages                   null         nantes   
4        erling skakkes gate 78                   null        stavern   
5               5677 strong st.                   null     san rafael   
6               ul. filtrowa 68                   null       warszawa   
7                 lyonerstr. 34                   null      frankfurt   
8     5557 north pendale street                   null  san francisco   
9       897 long airport avenue                   null            nyc   

  customers.state customers.postalcode customers.country  \
0            null                44000            france   
1              nv                83030               usa   
2        victoria                 3004         australia   
3            null                44000            france   
4            null                 4110            norway   
5              ca                97562               usa   
6            null               01-012            poland   
7            null                60528           germany   
8              ca                94217               usa   
9              ny                10022               usa   

   customers.salesrepemployeenumber  customers.creditlimit  
0                            1370.0                21000.0  
1                            1166.0                71800.0  
2                            1611.0               117300.0  
3                            1370.0               118200.0  
4                            1504.0                81700.0  
5                            1165.0               210500.0  
6                               NaN                    0.0  
7                            1504.0                59700.0  
8                            1165.0                64600.0  
9                            1323.0               114900.0

In [26]:
#     4. Get customernumber, customername, phone from customers table
pd.read_sql('SELECT * FROM customers LIMIT 10', hive_cnx)

customers.customernumber        customers.customername  \
0                       103             atelier graphique   
1                       112            signal gift stores   
2                       114    australian collectors, co.   
3                       119             la rochelle gifts   
4                       121            baane mini imports   
5                       124  mini gifts distributors ltd.   
6                       125            havel & zbyszek co   
7                       128          blauer see auto, co.   
8                       129               mini wheels co.   
9                       131             land of toys inc.   

  customers.contactlastname customers.contactfirstname    customers.phone  \
0                   schmitt                    carine          40.32.2555   
1                      king                       jean         7025551838   
2                  ferguson                      peter       03 9520 4555   
3                   labrune                    janine          40.67.8555   
4                bergulfsen                     jonas          07-98 9555   
5                    nelson                      susan         4155551450   
6           piestrzeniewicz                   zbyszek       (26) 642-7555   
7                    keitel                     roland  +49 69 66 90 2555   
8                    murphy                      julie         6505555787   
9                       lee                       kwai         2125557818   

         customers.addressline1 customers.addressline2 customers.city  \
0                54, rue royale                   null         nantes   
1               8489 strong st.                   null      las vegas   
2             636 st kilda road                level 3      melbourne   
3  67, rue des cinquante otages                   null         nantes   
4        erling skakkes gate 78                   null        stavern   
5               5677 strong st.                   null     san rafael   
6               ul. filtrowa 68                   null       warszawa   
7                 lyonerstr. 34                   null      frankfurt   
8     5557 north pendale street                   null  san francisco   
9       897 long airport avenue                   null            nyc   

  customers.state customers.postalcode customers.country  \
0            null                44000            france   
1              nv                83030               usa   
2        victoria                 3004         australia   
3            null                44000            france   
4            null                 4110            norway   
5              ca                97562               usa   
6            null               01-012            poland   
7            null                60528           germany   
8              ca                94217               usa   
9              ny                10022               usa   

   customers.salesrepemployeenumber  customers.creditlimit  
0                            1370.0                21000.0  
1                            1166.0                71800.0  
2                            1611.0               117300.0  
3                            1370.0               118200.0  
4                            1504.0                81700.0  
5                            1165.0               210500.0  
6                               NaN                    0.0  
7                            1504.0                59700.0  
8                            1165.0                64600.0  
9                            1323.0               114900.0

# Exercise

In this exercise we will create a CSV file with specific data from the customers table by following these steps:

1. Write an SQL query for customers whose number is between 124 and 131 (or any reasonable alternative)
2. Fetch the data from the table into a list of records.
3. Instantiate a DataFrame with the data and use the to_csv() method to creat the file.

# solution

In [40]:
# 1. Write an SQL query for customers whose number is between 124 and 131 (or any reasonable alternative)
query = "SELECT customernumber, customername, phone FROM customers WHERE customernumber BETWEEN 124 AND 131"

# 2. Fetch the data from the table into a list of records.

# option = 'A'
option = 'A' # 'B'
if option == 'A':
    with hive_cnx.cursor() as c:
        c.execute(query)
        results = c.fetchall()
    df = pd.DataFrame(results, columns=['customernumber', 'customername', 'phone'])
else:  # option B
    df = pd.read_sql(query, hive_cnx)
df = df.set_index('customernumber') # first column is the index
display(df)

# 3. Instantiate a DataFrame with the data and use the to_csv() method to creat the file.
df.to_csv('/home/naya/tutorial/sqoop/scripts/customers_sample.csv')


customername              phone
customernumber                                                 
124             mini gifts distributors ltd.         4155551450
125                       havel & zbyszek co      (26) 642-7555
128                     blauer see auto, co.  +49 69 66 90 2555
129                          mini wheels co.         6505555787
131                        land of toys inc.         2125557818